`MeasureToolbar`: modify `ArgumentException` message
Esri/arcgis-maps-sdk-dotnet-toolkit pull request #539
Opened 2024-01-03 23:51 UTC by williambohrmann3

When registering the `DependencyProperty`s for `LineSketchEditor` and `AreaSketchEditor`, they are both using the same method for the `PropertyMetadata` `PropertyChangedCallback` parameter. This is fine, but currently the exception message when the new value is null doesn't make sense for `AreaSketchEditor`. To remedy this, I would like to remove the unused method and modify the currently used method to make sense in both cases.

Also, I removed some redundant "using" statements and corrected a typo.

2024-01-04 18:35 UTC, williambohrmann3 commented
Any idea why the job might fail if the solution is building for me locally?

2024-01-04 19:51 UTC, williambohrmann3 commented
All resolved - updated the certificate for UWP, changes included in this PR.

2024-01-04 23:09 UTC, dotMorten requested changes

2024-01-04 23:09 UTC, dotMorten commented on src/Toolkit/Toolkit.UI.Controls/MeasureToolbar/MeasureToolbar.cs
> +        private static void OnSketchEditorPropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
Why this change? It's literally the 'LineSketchEditor' property. Please undo

2024-01-04 23:09 UTC, dotMorten commented on src/Toolkit/Toolkit.UI.Controls/MeasureToolbar/MeasureToolbar.cs
> -            DependencyProperty.Register(nameof(AreaSketchEditor), typeof(SketchEditor), typeof(MeasureToolbar), new PropertyMetadata(null, OnLineSketchEditorPropertyChanged));
This is the only bug. It should call  OnAreaSketchEditorPropertyChanged instead, and don't delete the code below.

2024-01-05 20:01 UTC, dotMorten approved these changes

2024-01-05 20:16 UTC, merged